#!/bin/bash
accelerate launch --num_processes 8 /data/phd/kousiqi/zhitao/DiffSynth-Studio/examples/qwen_image/model_training/train.py \
  --dataset_base_path "/" \
  --dataset_metadata_path "/data/phd/kousiqi/zhitao/metadata_all_products_expanded_optimized.json" \
  --data_file_keys "image,edit_image" \
  --extra_inputs "edit_image" \
  --max_pixels 1048576 \
  --dataset_repeat 1 \
  --model_id_with_origin_paths "Qwen/Qwen-Image-Edit-2511:transformer/diffusion_pytorch_model*.safetensors,Qwen/Qwen-Image:text_encoder/model*.safetensors,Qwen/Qwen-Image:vae/diffusion_pytorch_model.safetensors" \
  --learning_rate 1e-4 \
  --num_epochs 50 \
  --save_steps 1000 \
  --remove_prefix_in_ckpt "pipe.dit." \
  --output_path "/data/phd/kousiqi/zhitao/lora_all_products_rewrite_expanded_resume_149000" \
  --lora_base_model "dit" \
  --lora_target_modules "to_q,to_k,to_v,add_q_proj,add_k_proj,add_v_proj,to_out.0,to_add_out,img_mlp.net.2,img_mod.1,txt_mlp.net.2,txt_mod.1" \
  --lora_rank 128 \
  --lora_checkpoint "/data/phd/kousiqi/zhitao/lora_all_products_rewrite_expanded_resume_130000/step-19000.safetensors" \
  --use_gradient_checkpointing \
  --dataset_num_workers 0 \
  --find_unused_parameters \
  --zero_cond_t